name: firstcall
region: blr

services:
  - name: web
    github:
      repo: Divyanshu1Dubey/FirstCall
      branch: master
      deploy_on_push: true

    environment_slug: python
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 8080

    build_command: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    run_command: gunicorn disease_prediction.wsgi --workers 2 --threads 2 --timeout 120 --bind 0.0.0.0:$PORT

    health_check:
      http_path: /

    envs:
      - key: SECRET_KEY
        value: "change-this-to-a-50-char-random-string"
        type: SECRET
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "${APP_DOMAIN}"
      - key: DJANGO_SETTINGS_MODULE
        value: disease_prediction.settings
      - key: MISTRAL_API_KEY
        value: "PRodJoKYKf57GEf6zWmRcRs7AU4EgCA4"
        type: SECRET
      - key: GROQ_API_KEY
        value: "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"
        type: SECRET
      - key: GEMINI_API_KEY
        value: "AIzaSyDZM9XgQtbvy3ygDnnYnHiSlFdT4jaPMjc"
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${firstcall-db.DATABASE_URL}

databases:
  - name: firstcall-db
    engine: PG
    version: "16"
    size: db-s-dev-database
    num_nodes: 1
